Repository twitch4j/twitch4j, pull requests merged in 2020-10, with the labels that each got.

#212 docs: add cheermotes and codes markdown docs
  docs/content/rest-helix/_index.md
  docs/content/rest-helix/bits-cheermotes.md
  docs/content/rest-helix/entitlements-codes.md
  docs/content/rest-helix/entitlements-redeem-codes.md
Labels: docs, hacktoberfest

#211 feat: handle unofficial radio events pubsub topic
  pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/RadioData.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/RadioTrack.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/events/RadioEvent.java
Labels: feature

#209 feat: add channel follow count update event to client helper
  build.gradle
  twitch4j/src/main/java/com/github/twitch4j/TwitchClientHelper.java
  twitch4j/src/main/java/com/github/twitch4j/domain/ChannelCache.java
  twitch4j/src/main/java/com/github/twitch4j/events/ChannelFollowCountUpdateEvent.java
Labels: feature

#208 feat: add hype train badge support and update scopes
  auth/src/main/java/com/github/twitch4j/auth/domain/TwitchScopes.java
  common/src/main/java/com/github/twitch4j/common/enums/CommandPermission.java
  common/src/main/java/com/github/twitch4j/common/util/TwitchUtils.java
  rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKrakenErrorDecoder.java
  rest-kraken/src/test/java/kraken/endpoints/AbstractKrakenServiceTest.java
Labels: enhancement

#210 feat: handle unban request pubsub topic for channels and users
  pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/CreatedUnbanRequest.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/UnbanRequest.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/UpdatedUnbanRequest.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/events/ChannelUnbanRequestCreateEvent.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/events/ChannelUnbanRequestUpdateEvent.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/events/UnbanRequestEvent.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/events/UserUnbanRequestUpdateEvent.java
Labels: feature

#216 feat: fire specialized event on USERSTATE
  chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
  chat/src/main/java/com/github/twitch4j/chat/events/channel/UserStateEvent.java
Labels: feature, hacktoberfest

#214 feat: fire specialized mod/vip list event upon chat notice
  build.gradle
  chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
  chat/src/main/java/com/github/twitch4j/chat/events/channel/ListModsEvent.java
  chat/src/main/java/com/github/twitch4j/chat/events/channel/ListVipsEvent.java
Labels: enhancement

#219 fix: register jackson modules despite exotic class loaders
  build.gradle
  common/build.gradle
  common/src/main/java/com/github/twitch4j/common/util/TypeConvert.java
  rest-extensions/src/main/java/com/github/twitch4j/extensions/TwitchExtensionsBuilder.java
  rest-helix/build.gradle
  rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
  rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelixBuilder.java
  rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelixErrorDecoder.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/CategorySearchList.java
  rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKrakenBuilder.java
  rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKrakenErrorDecoder.java
  rest-tmi/src/main/java/com/github/twitch4j/tmi/TwitchMessagingInterfaceBuilder.java
  rest-tmi/src/main/java/com/github/twitch4j/tmi/TwitchMessagingInterfaceErrorDecoder.java
Labels: bug/major

#221 docs: add missing TMI docs and rename get-viewers
  docs/content/rest-tmi/_index.md
  docs/content/rest-tmi/get-chatters.md
  docs/content/rest-tmi/get-hosts-of.md
  docs/content/rest-tmi/get-hosts.md
Labels: docs, hacktoberfest

#222 docs: add moderators and getStreamKey Helix docs
  docs/content/rest-helix/_index.md
  docs/content/rest-helix/moderators-get-events.md
  docs/content/rest-helix/moderators-get.md
  docs/content/rest-helix/streams-get-key.md
Labels: docs, hacktoberfest

#224 docs: javadoc aggregation and delombok
  .gitignore
  build.gradle
  deployment.gradle
Labels: docs, enhancement
