Repository twitch4j/twitch4j, pull requests merged in 2020-09, with the labels that each got.

#191 fix: deserialize pagination in extension transaction list
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ExtensionTransaction.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ExtensionTransactionList.java
Labels: bug/minor

#190 feat: add get drops entitlements endpoint to helix
  rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/DropsEntitlement.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/DropsEntitlementList.java
Labels: feature

#194 docs: improve clarity of channel ids in pubsub
  docs/content/pubsub/topic-bits-badge-unlocks.md
  docs/content/pubsub/topic-bits-events.md
  docs/content/pubsub/topic-commerce-events.md
  docs/content/pubsub/topic-moderation-events.md
  docs/content/pubsub/topic-subscribe-events.md
  pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
Labels: docs

#187 feat: improve utility of active extensions in helix
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ActiveExtension.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/Extension.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ExtensionActiveList.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ExtensionList.java
Labels: feature

#188 feat: provide channel id + name in all events
  chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
  chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
  chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java
Labels: enhancement

#200 docs: add code of conduct and link contributing guide in readme
  CODE_OF_CONDUCT.md
  README.md
Labels: docs

#199 feat: add more host and chatter info to tmi
  rest-tmi/src/main/java/com/github/twitch4j/tmi/domain/Chatters.java
  rest-tmi/src/main/java/com/github/twitch4j/tmi/domain/Host.java
Labels: enhancement
