Repository twitch4j/twitch4j, pull requests merged in 2021-08, with the labels that each got.

#328 feat: implement user authorization grant v1 eventsub
  eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/UserAuthorizationGrantCondition.java
  eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/UserAuthorizationGrantEvent.java
  eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java
  eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/UserAuthorizationGrantType.java
Labels: feature

#386 feat: implement new helix schedule api
  common/src/main/java/com/github/twitch4j/common/util/TypeConvert.java
  rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ScheduleSegmentInput.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ScheduledSegment.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ScheduledVacation.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/StreamSchedule.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/StreamScheduleResponse.java
Labels: feature

#407 feat: add new fields to helix banned routes
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/BannedEvent.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/BannedUser.java
Labels: enhancement

#422 fix: jackson bom -> api
  build.gradle.kts
Labels: bug/minor

#417 chore: deprecate helix webhooks due to twitch announcement
  rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/WebhookSubscription.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/WebhookSubscriptionList.java
  rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/domain/WebhookNotification.java
  rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/domain/WebhookRequest.java
  rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/topics/ChannelBanTopic.java
  rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/topics/ChannelSubscriptionTopic.java
  rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/topics/ExtensionTransactionsTopic.java
  rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/topics/FollowsTopic.java
  rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/topics/HypeTrainTopic.java
  rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/topics/ModeratorChangeTopic.java
  rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/topics/StreamsTopic.java
  rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/topics/TwitchWebhookTopic.java
  rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/topics/UsersTopic.java
Labels: docs

#380 feat: implement channel.subscription.message v1 eventsub
  eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/ChannelSubscriptionMessageCondition.java
  eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/Message.java
  eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelSubscriptionMessageEvent.java
  eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelUnsubscribeEvent.java
  eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelSubscriptionGiftType.java
  eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelSubscriptionMessageType.java
  eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java
Labels: feature

#425 fix: store emote id as string in sub events over pubsub
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/CommerceMessage.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/SubGiftData.java
Labels: bug/minor

#427 feat: add more unofficial fields for pubsub hype trains
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/HypeTrainConductorUser.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/HypeTrainConfig.java
Labels: enhancement

#426 feat: support new emote api url template fields
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/Emote.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/EmoteList.java
Labels: enhancement
