Repository twitch4j/twitch4j, pull requests merged in 2021-04, with the labels that each got.

#302 feat: add unofficial badge endpoints
  rest-tmi/src/main/java/com/github/twitch4j/tmi/TwitchMessagingInterface.java
  rest-tmi/src/main/java/com/github/twitch4j/tmi/domain/Badge.java
  rest-tmi/src/main/java/com/github/twitch4j/tmi/domain/BadgeSet.java
  rest-tmi/src/main/java/com/github/twitch4j/tmi/domain/BadgeSets.java
Labels: feature

#298 feat: add sendMessage with nonce or reply to ITwitchChat
  chat/src/main/java/com/github/twitch4j/chat/ITwitchChat.java
  chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
  chat/src/main/java/com/github/twitch4j/chat/TwitchChatConnectionPool.java
Labels: enhancement

#287 feat: include eventsub cost fields for RFC 0014
  eventsub-common/src/main/java/com/github/twitch4j/eventsub/EventSubSubscription.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/EventSubSubscriptionList.java
Labels: enhancement

#308 feat: add Video#getThumbnailUrl(int, int)
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/Video.java
Labels: enhancement

#311 feat: add viewer event to client helper and channel cache getter
  twitch4j/src/main/java/com/github/twitch4j/TwitchClientHelper.java
  twitch4j/src/main/java/com/github/twitch4j/domain/ChannelCache.java
  twitch4j/src/main/java/com/github/twitch4j/events/ChannelViewerCountUpdateEvent.java
Labels: feature

#320 fix: resolve pubsub reconnect loop from ping edge case
  pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
Labels: bug/minor

#317 chore: bump caffeine dependency from 2.8.6 to 2.9.0
  build.gradle
Labels: dependencies

#319 feat: include new helix fields from april 15 update
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChannelInformation.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChannelSearchResult.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/Clip.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/Stream.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/Video.java
Labels: feature

#307 fix: include extendsub in SubscriptionType to avoid null context in pubsub
  common/src/main/java/com/github/twitch4j/common/enums/SubscriptionType.java
Labels: bug/minor, enhancement

#310 fix: correct unofficial subgift leaderboard pubsub topic name
  pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
Labels: bug/minor

#318 feat: add cheer badge to chat permissions
  chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java
  common/src/main/java/com/github/twitch4j/common/enums/CommandPermission.java
  common/src/main/java/com/github/twitch4j/common/util/TwitchUtils.java
Labels: enhancement

#309 chore: kraken hosts was decommissioned by twitch
  rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKraken.java
  rest-tmi/src/main/java/com/github/twitch4j/tmi/TwitchMessagingInterface.java
Labels: enhancement

#265 feat: add community goal support for channel points pubsub
  pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/CommunityGoalContribution.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/CommunityPointsGoal.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/events/CommunityGoalContributionEvent.java
Labels: enhancement

#322 feat: fire global user state chat event
  chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
  chat/src/main/java/com/github/twitch4j/chat/events/channel/GlobalUserStateEvent.java
  chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java
Labels: bug/minor, enhancement, feature

#323 feat: add new get followed streams helix endpoint
  auth/src/main/java/com/github/twitch4j/auth/domain/TwitchScopes.java
  rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
Labels: feature

#324 feat: add unofficial multi month chat tags
  chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
  chat/src/main/java/com/github/twitch4j/chat/events/channel/GiftSubscriptionsEvent.java
  chat/src/main/java/com/github/twitch4j/chat/events/channel/IRCMessageEvent.java
  chat/src/main/java/com/github/twitch4j/chat/events/channel/SubscriptionEvent.java
  common/src/main/java/com/github/twitch4j/common/util/TwitchUtils.java
Labels: enhancement

#321 feat: add community boost events unofficial pubsub topic
  pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/CommunityBoostOrder.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/CommunityBoostProgression.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/events/CommunityBoostProgressionEvent.java
Labels: feature

#312 feat: implement chat join ratelimit and improve thread efficiency
  chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
  chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
  chat/src/main/java/com/github/twitch4j/chat/util/TwitchChatLimitHelper.java
Labels: enhancement, feature

#306 feat: automatically handle helix rate limits
  rest-helix/build.gradle
  rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelixBuilder.java
  rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixClientIdInterceptor.java
  rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixDecoder.java
  rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixHttpClient.java
  twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
Labels: enhancement

#243 build(gradle): Kotlin DSL build and Dependabot
  .github/dependabot.yml
  .gitignore
  .gitlab-ci.yml
  CODE_OF_CONDUCT.md
  README.md
  auth/build.gradle
  auth/build.gradle.kts
  build.gradle
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/globals.kt
  buildSrc/src/main/kotlin/project.kt
  chat/build.gradle
  chat/build.gradle.kts
  common/build.gradle
  common/build.gradle.kts
  deployment.gradle
  eventsub-common/build.gradle
  eventsub-common/build.gradle.kts
  gradle.properties.template
  gradle/wrapper/gradle-wrapper.properties
  graphql/build.gradle
  graphql/build.gradle.kts
  pubsub/build.gradle
  pubsub/build.gradle.kts
  rest-extensions/build.gradle
  rest-extensions/build.gradle.kts
  rest-helix/build.gradle
  rest-helix/build.gradle.kts
  rest-kraken/build.gradle
  rest-kraken/build.gradle.kts
  rest-tmi/build.gradle
  rest-tmi/build.gradle.kts
  settings.gradle
  settings.gradle.kts
  twitch4j/build.gradle
  twitch4j/build.gradle.kts
Labels: enhancement
