Repository twitch4j/twitch4j, pull requests merged in 2022-01, with the labels that each got.

#491 feat: add low trust users unofficial pubsub topic
  pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/BanEvasionEvaluation.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/LowTrustUser.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/LowTrustUserNewMessage.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/LowTrustUserTreatment.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/LowTrustUserTreatmentUpdate.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/SimpleUser.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/events/LowTrustUserNewMessageEvent.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/events/LowTrustUserTreatmentUpdateEvent.java
Labels: feature

#502 fix: json unwrap custom reward settings on serialization
  rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelixBuilder.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/CustomReward.java
  rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/CustomRewardEncodeMixIn.java
Labels: bug/minor

#505 refactor: augment BanEvasionEvaluation and LowTrustUser.sender
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/BanEvasionEvaluation.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/LowTrustUser.java
Labels: enhancement

#503 feat: retry failed joins in irc with exponential backoff
  build.gradle.kts
  chat/build.gradle.kts
  chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
  chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
  chat/src/main/java/com/github/twitch4j/chat/TwitchChatConnectionPool.java
  chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelJoinFailureEvent.java
  chat/src/test/java/com/github/twitch4j/chat/ChatJoinRetryTest.java
  twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
  twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java
Labels: enhancement

#508 feat: support user intro chat experiment
  chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
  chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
  chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelMessageEvent.java
  chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelStateEvent.java
  chat/src/main/java/com/github/twitch4j/chat/events/channel/RitualEvent.java
Labels: feature

#506 feat: add the new_subscription creator goals type
  eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/GoalType.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/CreatorGoal.java
Labels: enhancement

#509 feat: add pubsub leaderboard time unit and video playback type
  pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/VideoPlaybackData.java
Labels: enhancement

#507 feat: add broadcaster login to ChannelInformation
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ChannelInformation.java
Labels: enhancement

#512 feat: allow for configurable helix base url
  rest-extensions/src/main/java/com/github/twitch4j/extensions/TwitchExtensionsBuilder.java
  rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelixBuilder.java
  rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKrakenBuilder.java
  twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
  twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java
Labels: enhancement

#513 fix: special messages can prevent triggering a ChannelMessageEvent
  chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
Labels: bug/minor

#515 feat: add unofficial chatrooms user pubsub topic
  pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/AliasRestrictionUpdateData.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/UserModerationActionData.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/VideoPlaybackData.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/events/AliasRestrictionUpdateEvent.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/events/UserModerationActionEvent.java
Labels: feature

#519 fix: ensure gql builder event manager has default handler
  common/src/main/java/com/github/twitch4j/common/util/EventManagerUtils.java
  graphql/src/main/java/com/github/twitch4j/graphql/TwitchGraphQLBuilder.java
Labels: bug/minor

#523 fix: make commandPrefixes non-final in builders
  chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
  chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
  twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
  twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java
  twitch4j/src/test/java/com/github/twitch4j/TwitchClientTest.java
Labels: bug/minor

#524 chore: promote helix moderation api methods out of beta
  rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
Labels: enhancement
