Repository twitch4j/twitch4j, pull requests merged in 2022-02, with the labels that each got.

#526 fix: remove control character suffix in action event message
  chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
  chat/src/main/java/com/github/twitch4j/chat/events/channel/ChannelMessageEvent.java
  chat/src/main/java/com/github/twitch4j/chat/util/ChatCrowdChant.java
Labels: enhancement

#525 feat: implement fetch unban requests via graphql
  graphql/src/main/graphql/com/github/twitch4j/graphql/internal/fetchUnbanRequests.graphql
  graphql/src/main/java/com/github/twitch4j/graphql/TwitchGraphQL.java
  graphql/src/main/java/com/github/twitch4j/graphql/command/CommandFetchUnbanRequests.java
Labels: feature

#533 chore: bump mockito to 4.3.1 and switch to the bom
  build.gradle.kts
  chat/build.gradle.kts
Labels: dependencies

#538 fix: add more status enums for pubsub polls
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/PollData.java
Labels: bug/minor

#534 docs: update soundtrack api javadoc by twitch revision
  rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackArtist.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/SoundtrackCurrentTrackWrapper.java
Labels: docs

#539 fix: enable ws rfc ping for chat and pubsub
  chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
  chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSubBuilder.java
  twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
  twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java
Labels: bug/minor

#529 feat: add helix extension api endpoints
  rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ExtensionBitsProduct.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ExtensionBitsProductList.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ExtensionConfigurationSegment.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ExtensionConfigurationSegmentInput.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ExtensionConfigurationSegmentList.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ExtensionLiveChannel.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ExtensionLiveChannelsList.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ExtensionSecret.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ExtensionSecrets.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ExtensionSecretsList.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ExtensionSegment.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ExtensionState.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ReleasedExtension.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/ReleasedExtensionList.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/SendPubSubMessageInput.java
  rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixClientIdInterceptor.java
Labels: feature
