Repository twitch4j/twitch4j, pull requests merged in 2022-08, with the labels that each got.

#617 fix: adjust clip event for helix time truncation
  twitch4j/src/main/java/com/github/twitch4j/TwitchClientHelper.java
Labels: enhancement

#618 refactor: use xanthic cache facade
  build.gradle.kts
  chat/build.gradle.kts
  chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
  chat/src/test/java/com/github/twitch4j/chat/ChatJoinRetryTest.java
  eventsub-common/build.gradle.kts
  eventsub-common/src/main/java/com/github/twitch4j/eventsub/util/EventSubVerifier.java
  graphql/build.gradle.kts
  graphql/src/main/java/com/github/twitch4j/graphql/TwitchGraphQL.java
  rest-helix/build.gradle.kts
  rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixRateLimitTracker.java
  rest-helix/src/main/java/com/github/twitch4j/helix/interceptor/TwitchHelixTokenManager.java
  twitch4j/build.gradle.kts
  twitch4j/src/main/java/com/github/twitch4j/TwitchClientHelper.java
Labels: enhancement

#620 fix: deserialize eventsub follow goal type
  eventsub-common/src/main/java/com/github/twitch4j/eventsub/domain/GoalType.java
Labels: bug/minor

#623 chore(deps): update dependency com.bucket4j.bucket4j-core to v8.0.1
  build.gradle.kts
  chat/build.gradle.kts
  common/build.gradle.kts
  rest-helix/build.gradle.kts
Labels: dependencies

#625 fix: prevent maven from using jackson3 snapshot
  build.gradle.kts
Labels: dependencies

#627 feat: allow custom websocket close delay
  auth/src/main/java/com/github/twitch4j/auth/TwitchAuth.java
  chat/src/main/java/com/github/twitch4j/chat/TwitchChat.java
  chat/src/main/java/com/github/twitch4j/chat/TwitchChatBuilder.java
  client-websocket/src/main/java/com/github/twitch4j/client/websocket/WebsocketConnection.java
  client-websocket/src/main/java/com/github/twitch4j/client/websocket/WebsocketConnectionConfig.java
  kotlin/src/test/kotlin/com/github/twitch4j/kotlin/mock/MockChat.kt
  pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSubBuilder.java
  twitch4j/src/main/java/com/github/twitch4j/TwitchClientBuilder.java
  twitch4j/src/main/java/com/github/twitch4j/TwitchClientPoolBuilder.java
Labels: enhancement

#628 feat: implement beta charity api
  auth/src/main/java/com/github/twitch4j/auth/domain/TwitchScopes.java
  chat/src/main/java/com/github/twitch4j/chat/events/IRCEventHandler.java
  chat/src/main/java/com/github/twitch4j/chat/events/channel/CharityDonationEvent.java
  common/src/main/java/com/github/twitch4j/common/util/DonationAmount.java
  eventsub-common/src/main/java/com/github/twitch4j/eventsub/condition/ChannelCharityCampaignCondition.java
  eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/ChannelCharityDonateEvent.java
  eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/ChannelCharityDonateType.java
  eventsub-common/src/main/java/com/github/twitch4j/eventsub/subscriptions/SubscriptionTypes.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/ITwitchPubSub.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/CharityCampaignStatus.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/domain/CharityDonationData.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/events/CharityCampaignDonationEvent.java
  pubsub/src/main/java/com/github/twitch4j/pubsub/events/CharityCampaignStatusEvent.java
  rest-helix/src/main/java/com/github/twitch4j/helix/TwitchHelix.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/CharityCampaign.java
  rest-helix/src/main/java/com/github/twitch4j/helix/domain/CharityCampaignWrapper.java
Labels: feature
